# https://medium.com/@szilardmatis/setup-redis-and-redisinsight-with-docker-compose-139de8bba7de

services:
  redis:
    image: redis:7.4.1-alpine
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - app-tier
    restart: always
  redis-insight:
    image: redis/redisinsight:2.60
    container_name: redis-insight
    hostname: redis-insight
    ports:
      - 5540:5540
    networks:
      - app-tier
    restart: always

networks:
  app-tier:
    external: true
