services:
  vernemq1:
    image: vernemq/vernemq
    container_name: vernemq1
    hostname: vernemq1
    ports:
      - "1883:1883"
    networks:
      - app-tier
    environment:
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
    restart: always

networks:
  app-tier:
    external: true
