# https://www.virtualizationhowto.com/2024/03/best-docker-containers-for-home-server-in-2024/
# https://github.com/louislam/uptime-kuma
version: '3.8'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - uptime-kuma:/app/data
    ports:
      - "3001:3001"  # <Host Port>:<Container Port>
    restart: always

volumes:
  uptime-kuma: