version: '3'
services:
  akhq:
    image: tchiotludo/akhq:latest
    hostname: akhq
    container_name: akhq
    # depends_on:
    #   - broker
    ports:
      - "8080:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "broker:29092"
              schema-registry:
                url: "http://schema-registry:8081"
              connect:
                - name: kafka-connect
                  url: "http://kafka-connect:8083"