# TODO: why user & pass incorect while tested

# TEST
# kafka-console-producer --broker-list localhost:9092 --topic test \
#   --producer.config <(echo -e "security.protocol=SASL_PLAINTEXT\n
#   sasl.mechanism=PLAIN\n
#   sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username=\"user\" password=\"user-secret\";")

services:
  zookeeper-server:
    image: bitnami/zookeeper:latest
    container_name: zookeeper-server
    hostname: zookeeper-server
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
    networks:
      - app-tier

  kafka-server:
    image: bitnami/kafka:latest
    container_name: kafka-server
    hostname: kafka-server
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-server:2181
      KAFKA_LISTENERS: SASL_PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://kafka-server:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_OPTS: -Djava.security.auth.login.config=/opt/bitnami/kafka/config/kafka_server_jaas.conf -Djava.security.debug=sasl -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: SASL_PLAINTEXT:SASL_PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
    ports:
      - '9092:9092'
    networks:
      - app-tier
    volumes:
      - ./kafka_server_jaas-bitnami.conf:/opt/bitnami/kafka/config/kafka_server_jaas.conf
    links:
      - zookeeper-server

volumes:
  kafka_data:

networks:
  app-tier:
    external: true
