services:
  kadeck:
    image: xeotek/kadeck:5.2.3
    container_name: kadeck
    hostname: kadeck
    ports:
      - "666:666"
    networks:
      - app-tier
    environment:
      - xeotek_kadeck_free=your_email@address.com
      - xeotek_kadeck_port=666
    volumes:
      - kadeck_data:/root/.kadeck/

volumes:
  kadeck_data:

networks:
  app-tier:
    external: true
