# https://www.pgadmin.org/docs/pgadmin4/development/container_deployment.html

services:
  postgres-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: postgres-pgadmin
    hostname: postgres-pgadmin
    ports:
      - "8080:80"
    networks:
      - app-tier
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=useruser123
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
      - PGADMIN_CONFIG_LOGIN_BANNER="Authorised users only!"
    volumes:
      - /var/lib/pgadmin/storage:/home/docker-container-files/pgadmin/storage
    restart: always

networks:
  app-tier:
    name: app-tier
    driver: bridge
