# https://hub.docker.com/_/postgres

services:
  postgres-modem-server:
    image: postgres:latest
    container_name: postgres-modem-server
    hostname: postgres-modem-server
    ports:
      - "5434:5432"
    networks:
      - app-tier
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespostgres123
      POSTGRES_DB: ICONICS
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /opt/postgres-modem-server/var/lib/postgresql/data:/var/lib/postgresql/data
      - /opt/postgres-modem-server/etc/postgresql:/etc/postgresql
    restart: always

volumes:
  pgdata:

networks:
  app-tier:
    name: app-tier
    driver: bridge
